
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDH", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToDH")
    @ResponseWrapper(localName = "conversionEuroToDHResponse", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToDHResponse")
    @Action(input = "http://ws/BanqueService/conversionEuroToDHRequest", output = "http://ws/BanqueService/conversionEuroToDHResponse")
    public double conversionEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://ws/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://ws/", className = "proxy.CompteListResponse")
    @Action(input = "http://ws/BanqueService/compteListRequest", output = "http://ws/BanqueService/compteListResponse")
    public List<Compte> compteList();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComtpe", targetNamespace = "http://ws/", className = "proxy.GetComtpe")
    @ResponseWrapper(localName = "getComtpeResponse", targetNamespace = "http://ws/", className = "proxy.GetComtpeResponse")
    @Action(input = "http://ws/BanqueService/getComtpeRequest", output = "http://ws/BanqueService/getComtpeResponse")
    public Compte getComtpe(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

}
